In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sn
import warnings

warnings.filterwarnings('ignore')

data1=pd.read_csv('/content/drive/MyDrive/280k_data/ack_h.csv')
data2=pd.read_csv('/content/drive/MyDrive/280k_data/benign_traffic_h.csv')
data3=pd.read_csv('/content/drive/MyDrive/280k_data/junk_h.csv')
data4=pd.read_csv('/content/drive/MyDrive/280k_data/scan_h.csv')
data5=pd.read_csv('/content/drive/MyDrive/280k_data/syn_h.csv')
data6=pd.read_csv('/content/drive/MyDrive/280k_data/tcp_h.csv')
data7=pd.read_csv('/content/drive/MyDrive/280k_data/udp_h.csv')
data8=pd.read_csv('/content/drive/MyDrive/280k_data/udpplain_h.csv')



data1['class']='ack'
data2['class']='benign'
data3['class']='junk'
data4['class']='scan'
data5['class']='syn'
data6['class']='tcp'
data7['class']='udp'
data8['class']='udpplain'


data=pd.concat([data1,data2,data3,data4,data5,data6,data7,data8],

               axis=0, sort=False, ignore_index=True)

data.groupby('class')['class'].count()
data

MI_dir_L5_weight  MI_dir_L5_mean  MI_dir_L5_variance  \
0               1.000000      566.000000        0.000000e+00   
1               1.996585      566.000000        5.820000e-11   
2               2.958989      566.000000        0.000000e+00   
3               3.958979      566.000000        0.000000e+00   
4               4.914189      566.000000        1.160000e-10   
...                  ...             ...                 ...   
279987         39.256165      504.003978        2.219839e+04   
279988         40.255905      505.245933        2.170751e+04   
279989         41.255606      506.427690        2.123756e+04   
279990         42.255469      507.553516        2.078725e+04   
279991         43.240249      508.627665        2.035525e+04   

        MI_dir_L3_weight  MI_dir_L3_mean  MI_dir_L3_variance  \
0               1.000000      566.000000        0.000000e+00   
1               1.997950      566.000000        5.820000e-11   
2               2.975291      566.000000        5.820000e-11   
3               3.975285      566.000000        0.000000e+00   
4               4.948239      566.000000        5.820000e-11   
...                  ...             ...                 ...   
279987         66.495961      426.545257        4.671683e+04   
279988         67.495697      428.433595        4.626179e+04   
279989         68.495396      430.266805        4.581322e+04   
279990         69.495260      432.047260        4.537113e+04   
279991         70.480240      433.777571        4.493541e+04   

        MI_dir_L1_weight  MI_dir_L1_mean  MI_dir_L1_variance  \
0               1.000000      566.000000        0.000000e+00   
1               1.999316      566.000000        0.000000e+00   
2               2.991729      566.000000        5.820000e-11   
3               3.991727      566.000000        1.160000e-10   
4               4.982654      566.000000        5.820000e-11   
...                  ...             ...                 ...   
279987        259.096457      328.198231        6.054598e+04   
279988        260.096115      329.066378        6.050847e+04   
279989        261.095728      329.927877        6.046976e+04   
279990        262.095555      330.782802        6.042988e+04   
279991        263.076671      331.631290        6.038885e+04   

        MI_dir_L0.1_weight  ...  HpHp_L0.1_covariance  HpHp_L0.1_pcc  \
0                 1.000000  ...                   0.0            0.0   
1                 1.999932  ...                   0.0            0.0   
2                 2.999171  ...                   0.0            0.0   
3                 3.999171  ...                   0.0            0.0   
4                 4.998261  ...                   0.0            0.0   
...                    ...  ...                   ...            ...   
279987         2788.201337  ...                   0.0            0.0   
279988         2789.200968  ...                   0.0            0.0   
279989         2790.200553  ...                   0.0            0.0   
279990         2791.200369  ...                   0.0            0.0   
279991         2792.180258  ...                   0.0            0.0   

        HpHp_L0.01_weight  HpHp_L0.01_mean  HpHp_L0.01_std  \
0                1.000000            566.0        0.000000   
1                1.000000            566.0        0.000000   
2                1.000000            566.0        0.000000   
3                1.000000            566.0        0.000000   
4                1.000000            566.0        0.000000   
...                   ...              ...             ...   
279987        3132.118867            554.0        0.000037   
279988        3133.118826            554.0        0.000037   
279989        3134.118779            554.0        0.000037   
279990        3135.118758            554.0        0.000039   
279991        3136.116499            554.0        0.000037   

        HpHp_L0.01_magnitude  HpHp_L0.01_radius  HpHp_L0.01_covariance  \
0                

In [ ]:
x=data['class'].unique()
x

array(['ack', 'benign', 'junk', 'scan', 'syn', 'tcp', 'udp', 'udpplain'],
      dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data["class"]= le.fit_transform(data["class"])

In [ ]:
x=data['class'].unique()
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
data_np = np.array(data) 
data_np

array([[1.00000000e+00, 5.66000000e+02, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.99658498e+00, 5.66000000e+02, 5.82000000e-11, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.95898885e+00, 5.66000000e+02, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [4.12556058e+01, 5.06427690e+02, 2.12375563e+04, ...,
        0.00000000e+00, 0.00000000e+00, 7.00000000e+00],
       [4.22554694e+01, 5.07553516e+02, 2.07872480e+04, ...,
        0.00000000e+00, 0.00000000e+00, 7.00000000e+00],
       [4.32402490e+01, 5.08627665e+02, 2.03552463e+04, ...,
        0.00000000e+00, 0.00000000e+00, 7.00000000e+00]])

In [ ]:
pip install fuzzy-c-means

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Attempting uninstall: typer
    Found existing installation: typer 0.4.2
    Uninstalling typer-0.4.2:
      Successfully uninstalled typer-0.4.2


In [ ]:
from fcmeans import FCM
fcm = FCM(n_clusters=2)
fcm.fit(data_np)

In [ ]:
fcm_labels = fcm.predict(data_np)
fcm_labels

array([1, 0, 0, ..., 1, 1, 1])

In [ ]:
np.unique(fcm_labels)

array([0, 1])

**Adjusted Rand Index**

In [ ]:
from sklearn import metrics
metrics.adjusted_rand_score(fcm_labels, data["class"]) 

0.027725837623756595

**Fowlkes-Mallows score**

In [ ]:
metrics.fowlkes_mallows_score(fcm_labels, data["class"]) 

0.3594228232107765