In [ ]:
import numpy as np
import pandas as pd
from xgboost import XGBClassifier
import matplotlib.pyplot as plt
import seaborn as sn
import warnings
warnings.filterwarnings('ignore')

data1=pd.read_csv('/content/drive/MyDrive/280k_data/ack_h.csv')
data2=pd.read_csv('/content/drive/MyDrive/280k_data/benign_traffic_h.csv')
data3=pd.read_csv('/content/drive/MyDrive/280k_data/junk_h.csv')
data4=pd.read_csv('/content/drive/MyDrive/280k_data/scan_h.csv')
data5=pd.read_csv('/content/drive/MyDrive/280k_data/syn_h.csv')
data6=pd.read_csv('/content/drive/MyDrive/280k_data/tcp_h.csv')
data7=pd.read_csv('/content/drive/MyDrive/280k_data/udp_h.csv')
data8=pd.read_csv('/content/drive/MyDrive/280k_data/udpplain_h.csv')


data1['class']='ack'
data2['class']='benign'
data3['class']='junk'
data4['class']='scan'
data5['class']='syn'
data6['class']='tcp'
data7['class']='udp'
data8['class']='udpplain'

data=pd.concat([data1,data2,data3,data4,data5,data6,data7,data8],axis=0, sort=False, ignore_index=True)
data.groupby('class')['class'].count()
data

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
X=data['class'].unique()
X

array(['ack', 'benign', 'junk', 'scan', 'syn', 'tcp', 'udp', 'udpplain'],
      dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data["class"]= le.fit_transform(data["class"])

In [ ]:
data["class"]

0         0
1         0
2         0
3         0
4         0
         ..
279987    7
279988    7
279989    7
279990    7
279991    7
Name: class, Length: 279992, dtype: int64

In [ ]:
X=data['class'].unique()
X

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
from matplotlib import pyplot as plt
import seaborn as sns
sns.set()
from sklearn.datasets import make_blobs
from sklearn.cluster import Birch

In [ ]:
data, y = make_blobs(n_samples=279992, centers=8, cluster_std=0.3, random_state=0)
print('Dataset Size : ',data.shape, y.shape)

Dataset Size :  (279992, 2) (279992,)


In [ ]:
y

array([3, 7, 2, ..., 7, 1, 5])

In [ ]:
from sklearn.cluster import Birch
model = Birch(branching_factor=30, n_clusters=5, threshold=2.5)
model.fit(data)
pred = model.predict(data)

In [ ]:
model_labels = model.predict(data)
model_labels

array([0, 1, 2, ..., 1, 2, 3])

In [ ]:
model.labels_

array([0, 1, 2, ..., 1, 2, 3])

**adjusted_rand_score**

In [ ]:
np.unique(model_labels)

array([0, 1, 2, 3])

In [ ]:
from sklearn import metrics
metrics.adjusted_rand_score(model_labels,y) 

0.534873916044383

**fowlkes_mallows_score**

In [ ]:
metrics.fowlkes_mallows_score(model_labels,y) 

0.6666576716200425